<?php

namespace Database\Seeders;

use App\Enums\EventCategory;
use App\Enums\EventSession;
use App\Enums\EventStatus;
use App\Models\Event;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $events = [
            [
                'title' => 'Design Systems Workshop',
                'description' => '<p>A hands-on workshop covering modern design systems, component libraries, and design tokens. Learn how to build scalable and consistent UIs across products.</p><h3>What You Will Learn</h3><ul><li>Atomic design methodology</li><li>Design token systems</li><li>Component library architecture</li></ul>',
                'start_date' => now()->addDays(7),
                'end_date' => now()->addDays(7),
                'registration_start' => now()->subDays(10),
                'registration_end' => now()->addDays(5),
                'location' => "UDINUS H.4",
                'quota' => 50,
                'registered_count' => 12,
                'banner' => "events/banners/image-1.jpg",
                'price' => 20000,
                'session' => EventSession::General->value,
                'status' => EventStatus::Published,
                'category' => EventCategory::RKT->value,
            ],
            [
                'title' => 'Startup Pitch Night',
                'description' => '<p>Connect with founders, investors, and mentors. Watch live startup pitches and network with the entrepreneurial community in Central Java.</p><h3>Agenda</h3><ol><li>Opening keynote by industry leader</li><li>5 startup pitches (10 min each)</li><li>Panel Q&A with investors</li><li>Networking session</li></ol>',
                'start_date' => now()->addDays(14),
                'end_date' => now()->addDays(14),
                'registration_start' => now()->subDays(5),
                'registration_end' => now()->addDays(12),
                'location' => 'Semarang — Auditorium A, UDINUS',
                'quota' => 250,
                'registered_count' => 189,
                'banner' => 'events/banners/image-2.jpg',
                'price' => 25000,
                'session' => EventSession::Networking->value,
                'status' => EventStatus::Published,
                'category' => EventCategory::NON_RKT->value,
            ],
            [
                'title' => 'AI & Machine Learning Summit',
                'description' => '<p>Explore the latest in AI research, machine learning applications, and ethical AI frameworks. Featuring keynotes from industry leaders and hands-on demo sessions.</p><h3>Topics</h3><ul><li>Large Language Models in production</li><li>Computer vision for real-world applications</li><li>Responsible AI development</li><li>MLOps and deployment strategies</li></ul>',
                'start_date' => now()->addDays(21),
                'end_date' => now()->addDays(22),
                'registration_start' => now(),
                'registration_end' => now()->addDays(19),
                'location' => 'UDINUS — Gedung H Lantai 4',
                'quota' => 2000,
                'registered_count' => 1205,
                'banner' => 'events/banners/image-3.jpg',
                'price' => 50000,
                'session' => EventSession::Data->value,
                'status' => EventStatus::Published,
                'category' => EventCategory::RKT->value,
            ],
            [
                'title' => 'UX Research Bootcamp',
                'description' => '<p>Intensive 2-day bootcamp on user research methods, usability testing, and data-driven design decisions. Perfect for designers and product managers looking to level up their research skills.</p><h3>Prerequisites</h3><ul><li>Basic understanding of UI/UX concepts</li><li>Laptop with Figma installed</li></ul>',
                'start_date' => now()->addDays(28),
                'end_date' => now()->addDays(29),
                'registration_start' => now()->addDays(3),
                'registration_end' => now()->addDays(26),
                'location' => 'Online — Google Meet',
                'quota' => 800,
                'registered_count' => 0,
                'banner' => 'events/banners/placeholder.jpg',
                'price' => 75000,
                'session' => EventSession::MediaCreative->value,
                'status' => EventStatus::Published,
                'category' => EventCategory::NON_RKT->value,
            ],
            [
                'title' => 'Open Source Meetup',
                'description' => '<p>Monthly meetup for open source contributors. Share projects, get code reviews, and contribute to popular repositories together.</p><p>Bring your laptop and be ready to code! We will have mentors available for newcomers who want to make their first contribution.</p>',
                'start_date' => now()->addDays(35),
                'end_date' => now()->addDays(35),
                'registration_start' => now()->addDays(10),
                'registration_end' => now()->addDays(33),
                'location' => 'UDINUS — Lab Komputer D.2',
                'quota' => 200,
                'registered_count' => 0,
                'banner' => 'events/banners/placeholder.jpg',
                'price' => 0,
                'session' => EventSession::Programming->value,
                'status' => EventStatus::Draft,
                'category' => EventCategory::ETC->value,
            ],
            [
                'title' => 'Cloud Architecture Day',
                'description' => '<p>Deep-dive into cloud-native architectures, serverless patterns, and distributed systems design. Learn best practices from certified cloud architects.</p><h3>Session Tracks</h3><ul><li>AWS vs GCP vs Azure comparison</li><li>Kubernetes in production</li><li>Serverless architecture patterns</li><li>Cost optimization strategies</li></ul>',
                'start_date' => now()->subDays(20),
                'end_date' => now()->subDays(20),
                'registration_start' => now()->subDays(50),
                'registration_end' => now()->subDays(22),
                'location' => 'UDINUS — Gedung H Lantai 3',
                'quota' => 1200,
                'registered_count' => 890,
                'banner' => 'events/banners/placeholder.jpg',
                'price' => 35000,
                'session' => EventSession::Networking->value,
                'status' => EventStatus::Published,
                'category' => EventCategory::RKT->value,
            ],
            [
                'title' => 'DOSCOM Open Recruitment 2026',
                'description' => '<p>Annual recruitment for new DOSCOM members. Join the largest open source community at Universitas Dian Nuswantoro and grow your skills together!</p><h3>What We Offer</h3><ul><li>Free workshops and mentorship</li><li>Real project experience</li><li>Community networking</li><li>Certificate of participation</li></ul><p><strong>Requirements:</strong> Active UDINUS student, any major welcome.</p>',
                'start_date' => now()->addDays(45),
                'end_date' => now()->addDays(60),
                'registration_start' => now()->addDays(15),
                'registration_end' => now()->addDays(43),
                'location' => 'Universitas Dian Nuswantoro',
                'quota' => 100,
                'registered_count' => 100,
                'banner' => "events/banners/image-2.jpg",
                'price' => 20000,
                'session' => EventSession::General->value,
                'status' => EventStatus::Draft,
                'category' => EventCategory::RECRUITMENT->value,
            ],
            [
                'title' => 'Hackathon: Code for Good',
                'description' => '<p>48-hour hackathon focused on building technology solutions for social impact. Form a team, pick a challenge, and build something that matters.</p><h3>Prizes</h3><ul><li>1st Place: Rp 5.000.000 + Internship opportunity</li><li>2nd Place: Rp 3.000.000</li><li>3rd Place: Rp 1.500.000</li></ul>',
                'start_date' => now()->subDays(45),
                'end_date' => now()->subDays(43),
                'registration_start' => now()->subDays(75),
                'registration_end' => now()->subDays(47),
                'location' => 'UDINUS — Gedung E Co-Lab',
                'quota' => 500,
                'registered_count' => 300,
                'banner' => 'events/banners/placeholder.jpg',
                'price' => 0,
                'session' => EventSession::Programming->value,
                'status' => EventStatus::Published,
                'category' => EventCategory::ETC->value,
            ],
            [
                'title' => 'Web Development Workshop',
                'description' => '<p>Learn modern web development from scratch! This workshop covers HTML, CSS, JavaScript, and an introduction to frameworks like Vue.js and Laravel.</p><h3>Schedule</h3><ul><li>Day 1: HTML & CSS fundamentals</li><li>Day 2: JavaScript essentials</li><li>Day 3: Introduction to Vue.js</li><li>Day 4: Backend with Laravel</li></ul>',
                'start_date' => now()->subDays(5),
                'end_date' => now()->addDays(2),
                'registration_start' => now()->subDays(30),
                'registration_end' => now()->subDays(7),
                'location' => 'Online — Zoom + Discord',
                'quota' => 300,
                'registered_count' => 298,
                'banner' => 'events/banners/placeholder.jpg',
                'price' => 15000,
                'session' => EventSession::Programming->value,
                'status' => EventStatus::Published,
                'category' => EventCategory::RKT->value,
            ],
            [
                'title' => 'Data Science Fundamentals',
                'description' => '<p>An introductory course to data science covering Python, pandas, data visualization, and basic machine learning concepts. No prior experience needed!</p><h3>Tools Used</h3><ul><li>Python 3.12</li><li>Jupyter Notebook</li><li>pandas & matplotlib</li><li>scikit-learn basics</li></ul>',
                'start_date' => now()->addDays(50),
                'end_date' => now()->addDays(52),
                'registration_start' => now()->addDays(20),
                'registration_end' => now()->addDays(48),
                'location' => 'UDINUS — Lab Komputer D.3',
                'quota' => 150,
                'registered_count' => 0,
                'banner' => "events/banners/image-3.jpg",
                'price' => 10000,
                'session' => EventSession::Data->value,
                'status' => EventStatus::Published,
                'category' => EventCategory::NON_RKT->value,
            ],
        ];

        collect($events)->each(fn (array $event) => Event::create($event));

        // Soft-delete the Hackathon event
        Event::where('title', 'Hackathon: Code for Good')->first()?->delete();
    }
}
