services:
    app:
        container_name: d_form_app
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./docker/Dockerfile.dev
            args:
                - UID=1000
                - GID=1000
        volumes:
            # Use consistent path format for Windows compatibility
            - .:/app:cached
            - /app/node_modules
            - /app/vendor
            - ./bootstrap/cache:/app/bootstrap/cache:rw
            - ./storage:/app/storage:rw
            - caddy_data:/data
            - caddy_config:/config
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
            - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini:ro
            # Let Octane generate Caddyfile automatically for FrankenPHP
            # - ./docker/caddy/Caddyfile:/etc/frankenphp/Caddyfile:ro
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - PHP_OPCACHE_REVALIDATE_FREQ=0
        dns:
            - 8.8.8.8
            - 8.8.4.4
        networks:
            - default
        depends_on:
            - db
            - redis
        restart: unless-stopped
        ports:
            - '3000:8000'
            - '5173:5173'
        # Command untuk development dengan watch mode
        command: --watch --workers=1

    db:
        container_name: d_form_db
        image: mysql:9.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - mysql_db:/var/lib/mysql
            # - ./docker/mysql/healthcheck.cnf:/etc/mysql/healthcheck.cnf:ro
        ports:
            - ${DB_PORT}:3306
        networks:
            - default
        # healthcheck:
        #     test: ['CMD', 'mysqladmin', '-p${DB_PASSWORD}', 'ping', '-h', 'localhost']
        #     timeout: 5s
        #     retries: 3

    phpmyadmin:
        image: phpmyadmin:apache
        container_name: d_form_phpmyadmin
        ports:
            - 8090:80
        expose:
            - 8090
        networks:
            - default
        depends_on:
            # db:
            #     condition: service_healthy
            - db
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_ARBITRARY=0

    redis:
        container_name: d_form_redis
        image: redis:8.0-alpine
        ports:
            - '${REDIS_PORT:-6379}:6379'
        restart: unless-stopped
        volumes:
            - redis_data:/data
        networks:
            - default
        command: >-
            redis-server
            --appendonly yes

networks:
    default:
        driver: bridge

volumes:
    mysql_db:
        driver: local
    redis_data:
        driver: local
    caddy_data:
    caddy_config:
