services:
    app:
        container_name: d_form_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile.dev
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
            - /app/vendor
            - caddy_data:/data
            - caddy_config:/config
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - PHP_OPCACHE_REVALIDATE_FREQ=0
            - DB_HOST=db
            - REDIS_HOST=redis
        dns:
            - 8.8.8.8
            - 8.8.4.4
        networks:
            - d-form-network
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started
        restart: unless-stopped
        ports:
            - '${APP_PORT:-3000}:8000'
            - '5173:5173'
        command: --watch --workers=1

    db:
        container_name: d_form_db
        image: mysql:9.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_DATABASE: ${DB_DATABASE:-d_form}
        volumes:
            - mysql_db:/var/lib/mysql
        ports:
            - '${DB_PORT:-3306}:3306'
        networks:
            - d-form-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-secret}"]
            retries: 3
            timeout: 5s
        restart: unless-stopped

    phpmyadmin:
        image: phpmyadmin:apache
        container_name: d_form_phpmyadmin
        ports:
            - '${PMA_PORT:-8090}:80'
        networks:
            - d-form-network
        depends_on:
            - db
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_ARBITRARY=1

    redis:
        container_name: d_form_redis
        image: redis:8.0-alpine
        ports:
            - '${REDIS_PORT:-6379}:6379'
        restart: unless-stopped
        volumes:
            - redis_data:/data
        networks:
            - d-form-network
        command: redis-server --appendonly yes

networks:
    d-form-network:
        driver: bridge

volumes:
    mysql_db:
        driver: local
    redis_data:
        driver: local
    caddy_data:
    caddy_config:
