import type { Component } from 'vue'

export type IconComponent = Component

export type CuratedIconName =
    | 'arrowRight'
    | 'arrowLeft'
    | 'arrowUpRight'
    | 'check'
    | 'close'
    | 'plus'
    | 'minus'
    | 'trash'
    | 'edit'
    | 'search'
    | 'settings'
    | 'calendar'
    | 'clock'
    | 'mapPin'
    | 'users'
    | 'mail'
    | 'lock'
    | 'eye'
    | 'eyeOff'
    | 'chevronRight'
    | 'chevronLeft'
    | 'chevronDown'
    | 'chevronUp'
    | 'menu'
    | 'bell'
    | 'logout'
    | 'externalLink'
    | 'copy'
    | 'download'
    | 'upload'
    | 'filter'
    | 'sort'
    | 'more'
    | 'home'
    | 'sparkles'
    | 'trendingUp'
    | 'trendingDown'
    | 'alertCircle'
    | 'info'
    | 'helpCircle'
    | 'qrCode'
    | 'image'
    | 'fileText'
    | 'link'
    | 'palette'
    | 'play'
    | 'pause'
    | 'refresh'
    | 'star'
    | 'send'
    | 'grip'
