/**
 * Curated icon allowlist.
 *
 * Rule: only re-export icons used for actual *actions* and *navigation*.
 * Decorative illustrations should use Lottie via `LocalLottie`.
 *
 * Adding a new icon: import it here AND add the key to `CuratedIconName`
 * in `@/types/icons.ts`. Avoid importing lucide directly elsewhere.
 */
import {
    ArrowRight,
    ArrowLeft,
    ArrowUpRight,
    Check,
    X,
    Plus,
    Minus,
    Trash2,
    Pencil,
    Search,
    Settings,
    Calendar,
    Clock,
    MapPin,
    Users,
    Mail,
    Lock,
    Eye,
    EyeOff,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    ChevronUp,
    Menu,
    Bell,
    LogOut,
    ExternalLink,
    Copy,
    Download,
    Upload,
    SlidersHorizontal,
    ArrowUpDown,
    MoreHorizontal,
    Home,
    Sparkles,
    TrendingUp,
    TrendingDown,
    AlertCircle,
    Info,
    HelpCircle,
    QrCode,
    Image as ImageIcon,
    FileText,
    Link as LinkIcon,
    Palette,
    Play,
    Pause,
    RefreshCw,
    Star,
    Send,
    GripVertical,
} from 'lucide-vue-next'

import type { CuratedIconName, IconComponent } from '@/types/icons'

export const icons = {
    arrowRight: ArrowRight,
    arrowLeft: ArrowLeft,
    arrowUpRight: ArrowUpRight,
    check: Check,
    close: X,
    plus: Plus,
    minus: Minus,
    trash: Trash2,
    edit: Pencil,
    search: Search,
    settings: Settings,
    calendar: Calendar,
    clock: Clock,
    mapPin: MapPin,
    users: Users,
    mail: Mail,
    lock: Lock,
    eye: Eye,
    eyeOff: EyeOff,
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    menu: Menu,
    bell: Bell,
    logout: LogOut,
    externalLink: ExternalLink,
    copy: Copy,
    download: Download,
    upload: Upload,
    filter: SlidersHorizontal,
    sort: ArrowUpDown,
    more: MoreHorizontal,
    home: Home,
    sparkles: Sparkles,
    trendingUp: TrendingUp,
    trendingDown: TrendingDown,
    alertCircle: AlertCircle,
    info: Info,
    helpCircle: HelpCircle,
    qrCode: QrCode,
    image: ImageIcon,
    fileText: FileText,
    link: LinkIcon,
    palette: Palette,
    play: Play,
    pause: Pause,
    refresh: RefreshCw,
    star: Star,
    send: Send,
    grip: GripVertical,
} as const satisfies Record<CuratedIconName, IconComponent>

export type { CuratedIconName, IconComponent }
